# Etapa 1 — Builder
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Etapa 2 — Runtime
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000


CMD ["npm", "run", "dev"]
